server:
  port: 1010

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
#    是否从其他服务中心同步服务列表
    fetch-registry: false
#    是否将自己作为服务注册到服务中心
    register-with-eureka: false
